//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocotorDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_UsersRoles
    {
        public string ID { get; set; }
        public string UserID { get; set; }
        public string RoleID { get; set; }
    
        public virtual Tbl_Roles Tbl_Roles { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
