//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocotorDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Item()
        {
            this.Tbl_Docotors = new HashSet<Tbl_Docotors>();
        }
    
        public string ID { get; set; }
        public string Item_Name { get; set; }
        public string Item_Description { get; set; }
        public string Item_Image { get; set; }
        public string Item_Location { get; set; }
        public string CategoryID { get; set; }
        public string UserID { get; set; }
    
        public virtual Tbl_Categories Tbl_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Docotors> Tbl_Docotors { get; set; }
        public virtual Tbl_Users Tbl_Users { get; set; }
    }
}
